import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {createStore,passwordHash,passwordMatches,hashToken,fail,positive} from './store.mjs';
export function createApp(options={}){const s=createStore(options.dbPath||process.env.DB_PATH||'./data/shop.sqlite'),{all,get,run,tx,audit}=s,origins=(process.env.PUBLIC_ORIGIN||'http://localhost:3000').split(',').map(x=>x.trim()),publicDir=fileURLToPath(new URL('../public/',import.meta.url)),limits=new Map();
const safeUser=u=>{if(!u)return null;const {password_hash,...v}=u;return v};
function createUser(d,role='customer',actor=null){if(!d.name?.trim()||!/^\S+@\S+\.\S+$/.test(d.email||'')||typeof d.password!=='string'||d.password.length<10||d.password.length>128)fail('Ім’я, email і пароль від 10 символів обов’язкові');if(!['customer','admin','seller','owner'].includes(role))fail('Некоректна роль');return tx(()=>{const id=Number(run('INSERT INTO users(name,email,phone,password_hash,role,finance_access) VALUES(?,?,?,?,?,?)',d.name.trim(),d.email.trim().toLowerCase(),d.phone||'',passwordHash(d.password),role,role==='owner'?1:0).lastInsertRowid);run(`INSERT INTO ${role==='customer'?'customers':'employees'}(user_id) VALUES(?)`,id);audit(actor,'user.create',id,role);return safeUser(get('SELECT * FROM users WHERE id=?',id))})}
if(!get("SELECT id FROM users WHERE role='owner'")&&process.env.OWNER_EMAIL&&process.env.OWNER_PASSWORD)createUser({name:process.env.OWNER_NAME||'Власник',email:process.env.OWNER_EMAIL,password:process.env.OWNER_PASSWORD},'owner');
function session(req){const token=/\bvs_session=([a-f0-9]+)/.exec(req.headers.cookie||'')?.[1];return token?get('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?',hashToken(token),Date.now()):null}
function authorize(u,roles){if(!u)fail('Потрібен вхід',401);if(roles&&!roles.includes(u.role))fail('Недостатньо прав доступу',403)}
function loginCookie(res,u){const token=randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',hashToken(token),u.id,Date.now()+7*86400000);const secure=origins.some(o=>o.startsWith('https://'));res.setHeader('Set-Cookie',`vs_session=${token}; HttpOnly; Path=/; Max-Age=604800; SameSite=${process.env.COOKIE_CROSS_SITE==='true'?'None':'Lax'}${secure?'; Secure':''}`)}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>150000)fail('Запит завеликий',413)}try{return text?JSON.parse(text):{}}catch{fail('Некоректний JSON')}}
const server=createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');const origin=req.headers.origin;if(origin&&origins.includes(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin')}if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.writeHead(204);return res.end()}
const send=(v,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(v))};
try{const url=new URL(req.url,'http://localhost'),path=url.pathname,method=req.method,q=Object.fromEntries(url.searchParams);if(!path.startsWith('/api/')){let pathname=decodeURIComponent(path);if(pathname==='/')pathname='/index.html';const file=resolve(publicDir,'.'+pathname);if(!file.startsWith(resolve(publicDir)+String.fromCharCode(92))&&!file.startsWith(resolve(publicDir)+'/'))fail('Не знайдено',404);const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.jpg':'image/jpeg','.webp':'image/webp','.png':'image/png'}[extname(file)];if(!mime)fail('Не знайдено',404);const bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime+'; charset=utf-8','Cache-Control':'no-cache'});return res.end(bytes)}
if(!['GET','HEAD'].includes(method)){if(origin&&!origins.includes(origin))fail('Заборонене джерело запиту',403);if(req.headers['sec-fetch-site']==='cross-site'&&!origin)fail('Заборонене джерело запиту',403);if(method!=='DELETE'&&!req.headers['content-type']?.startsWith('application/json'))fail('Потрібен application/json',415)}
const key=req.socket.remoteAddress||'unknown',now=Date.now(),lim=limits.get(key)||{start:now,count:0};if(now-lim.start>60000){lim.start=now;lim.count=0}lim.count++;limits.set(key,lim);if(lim.count>300)fail('Забагато запитів. Спробуйте за хвилину.',429);let u=session(req),d=['POST','PATCH'].includes(method)?await body(req):{};let match;
if(path==='/api/health')return send({ok:true});
if(path==='/api/products'&&method==='GET')return send(s.productRows(null,q));
if(path==='/api/auth/me'){authorize(u);return send(safeUser(u))}
if(path==='/api/auth/register'&&method==='POST'){const created=createUser(d);loginCookie(res,created);return send(created,201)}
if(path==='/api/auth/login'&&method==='POST'){const attemptsKey='login:'+key,attempts=limits.get(attemptsKey)||{start:now,count:0};if(now-attempts.start>60000){attempts.start=now;attempts.count=0}limits.set(attemptsKey,attempts);if(++attempts.count>8)fail('Забагато спроб входу',429);const found=get('SELECT * FROM users WHERE email=?',String(d.email||'').trim().toLowerCase());if(!found||!passwordMatches(String(d.password||''),found.password_hash))fail('Невірний email або пароль',401);loginCookie(res,found);return send(safeUser(found))}
if(path==='/api/auth/logout'&&method==='POST'){const token=/\bvs_session=([a-f0-9]+)/.exec(req.headers.cookie||'')?.[1];if(token)run('DELETE FROM sessions WHERE token=?',hashToken(token));res.setHeader('Set-Cookie','vs_session=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax');return send({ok:true})}
if(path==='/api/auth/forgot'&&method==='POST'){const found=get('SELECT id,email FROM users WHERE email=?',String(d.email||'').trim().toLowerCase());if(found){const token=randomBytes(32).toString('hex');tx(()=>{run('INSERT INTO password_resets(token,user_id,expires) VALUES(?,?,?)',hashToken(token),found.id,Date.now()+3600000);run('INSERT INTO notifications(user_id,channel,recipient,message,status) VALUES(?,?,?,?,?)',found.id,'email',found.email,`${origins[0]}/#/reset?token=${token}`,'not_configured')})}return send({ok:true})}
if(path==='/api/auth/reset'&&method==='POST'){if(typeof d.password!=='string'||d.password.length<10||d.password.length>128)fail('Пароль має містити 10–128 символів');tx(()=>{const row=get('SELECT * FROM password_resets WHERE token=? AND used=0 AND expires>?',hashToken(String(d.token||'')),now);if(!row)fail('Посилання недійсне або прострочене');run('UPDATE users SET password_hash=? WHERE id=?',passwordHash(d.password),row.user_id);run('UPDATE password_resets SET used=1 WHERE user_id=?',row.user_id);run('DELETE FROM sessions WHERE user_id=?',row.user_id)});return send({ok:true})}
if(path==='/api/profile'&&method==='PATCH'){authorize(u);if(!d.name?.trim()||!/^\S+@\S+\.\S+$/.test(d.email||''))fail('Перевірте ім’я та email');run('UPDATE users SET name=?,email=?,phone=?,city=?,branch=? WHERE id=?',d.name.trim(),d.email.trim().toLowerCase(),String(d.phone||''),String(d.city||''),String(d.branch||''),u.id);return send(safeUser(get('SELECT * FROM users WHERE id=?',u.id)))}
if(path==='/api/favorites'&&method==='GET'){authorize(u);return send(all('SELECT product_id id FROM favorites WHERE user_id=?',u.id))}
if((match=path.match(/^\/api\/favorites\/(\d+)$/))&&['POST','DELETE'].includes(method)){authorize(u);const id=positive(match[1]);if(!get('SELECT id FROM products WHERE id=?',id))fail('Товар не знайдено',404);if(method==='POST')run('INSERT OR IGNORE INTO favorites VALUES(?,?)',u.id,id);else run('DELETE FROM favorites WHERE user_id=? AND product_id=?',u.id,id);return send({ok:true})}
if((match=path.match(/^\/api\/products\/(\d+)\/reviews$/))){if(method==='GET')return send(all('SELECT r.id,r.rating,r.text,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? AND r.approved=1 ORDER BY r.id DESC',+match[1]));if(method==='POST'){authorize(u);const rating=positive(d.rating);if(rating>5||!d.text?.trim()||d.text.length>2000)fail('Перевірте оцінку та текст');run('INSERT INTO reviews(product_id,user_id,rating,text) VALUES(?,?,?,?)',+match[1],u.id,rating,d.text.trim());return send({ok:true},201)}}
if(path==='/api/orders'){if(method==='POST')return send(s.createOrder(d,u),201);authorize(u);return send(s.orderRows(u))}
if(path==='/api/pos/sales'&&method==='POST'){authorize(u,['owner','admin','seller']);return send(s.createOrder(d,u,'pos'),201)}
if(path.startsWith('/api/admin/')){authorize(u,['owner','admin','seller']);const section=path.split('/')[3];if(u.role==='seller'&&!['orders','expiry'].includes(section))fail('Недостатньо прав доступу',403);
if(path==='/api/admin/orders'&&method==='GET')return send(s.orderRows(u));
if((match=path.match(/^\/api\/admin\/orders\/(\d+)\/returns$/))&&method==='POST')return send(s.returnItems(+match[1],d,u));
if((match=path.match(/^\/api\/admin\/orders\/(\d+)$/))&&method==='PATCH'){if(u.role==='seller'&&!['Зібрано','Готове до видачі','Виконано'].includes(d.status))fail('Недостатньо прав для цього статусу',403);return send(s.updateStatus(+match[1],d,u))}
if(path==='/api/admin/products'&&method==='GET')return send(s.productRows(u,{limit:2000}));
if(path==='/api/admin/products'&&method==='POST')return send(s.saveProduct(d,u),201);
if((match=path.match(/^\/api\/admin\/products\/(\d+)$/))&&method==='PATCH')return send(s.saveProduct(d,u,+match[1]));
if(path==='/api/admin/stock'){if(method==='POST')return send(s.stockOperation(d,u));return send(all('SELECT m.*,p.name product,u.name employee FROM stock_movements m JOIN products p ON p.id=m.product_id LEFT JOIN users u ON u.id=m.employee_id ORDER BY m.id DESC LIMIT 1000'))}
if(path==='/api/admin/expiry')return send(all('SELECT l.id,l.product_id,p.name product,l.quantity,l.expiry FROM expiration_lots l JOIN products p ON p.id=l.product_id WHERE l.quantity>0 ORDER BY l.expiry'));
if(path==='/api/admin/overview')return send(s.overview(u,q));
if(path==='/api/admin/customers')return send(all("SELECT u.id,u.name,u.email,u.phone,u.created_at,(SELECT COUNT(*) FROM orders o WHERE o.user_id=u.id) orders FROM users u JOIN customers c ON c.user_id=u.id ORDER BY u.id DESC"));
if(path==='/api/admin/suppliers'){if(method==='POST'){if(!d.name?.trim())fail('Вкажіть назву');const id=Number(run('INSERT INTO suppliers(name,contact,phone,email,site,note) VALUES(?,?,?,?,?,?)',...['name','contact','phone','email','site','note'].map(k=>String(d[k]||''))).lastInsertRowid);audit(u,'supplier.create',id,d.name);return send({id},201)}return send(all('SELECT * FROM suppliers ORDER BY id DESC'))}
if((match=path.match(/^\/api\/admin\/suppliers\/(\d+)\/receipts$/)))return send(all('SELECT r.*,l.product_id,l.quantity,l.expiry'+(u.role==='owner'||u.finance_access?',l.cost':'')+' FROM stock_receipts r JOIN expiration_lots l ON l.receipt_id=r.id WHERE r.supplier_id=?',+match[1]));
if(path==='/api/admin/directories')return send({categories:all('SELECT * FROM categories'),brands:all('SELECT * FROM brands')});
if((match=path.match(/^\/api\/admin\/(categories|brands)(?:\/(\d+))?$/))&&['POST','PATCH'].includes(method)){if(!d.name?.trim())fail('Вкажіть назву');const [_,kind,id]=match;if(id)run(`UPDATE ${kind} SET name=? WHERE id=?`,d.name.trim(),+id);else s.dir(kind,d.name.trim());audit(u,'directory.save',kind,d.name);return send({ok:true})}
if(path==='/api/admin/reviews')return send(all('SELECT r.*,p.name product,u.name FROM reviews r JOIN products p ON p.id=r.product_id JOIN users u ON u.id=r.user_id ORDER BY r.id DESC'));
if((match=path.match(/^\/api\/admin\/reviews\/(\d+)$/))&&method==='PATCH'){run('UPDATE reviews SET approved=? WHERE id=?',d.approved?1:0,+match[1]);audit(u,'review.moderate',match[1],String(!!d.approved));return send({ok:true})}
if(path==='/api/admin/audit')return send(all('SELECT a.*,u.name employee FROM audit_log a LEFT JOIN users u ON u.id=a.employee_id ORDER BY a.id DESC LIMIT 1000'));
if(path==='/api/admin/notifications')return send(all("SELECT n.id,n.channel,n.status,n.created_at,o.code order_code,CASE WHEN n.channel='sms' THEN n.message ELSE 'Посилання відновлення пароля приховане' END message FROM notifications n LEFT JOIN orders o ON o.id=n.order_id ORDER BY n.id DESC LIMIT 1000"));
if(section==='employees'){authorize(u,['owner']);if(path==='/api/admin/employees'){if(method==='POST'){if(!['admin','seller'].includes(d.role))fail('Оберіть роль');return send(createUser(d,d.role,u),201)}return send(all("SELECT id,name,email,phone,role,finance_access FROM users WHERE role IN('owner','admin','seller')"))}if((match=path.match(/^\/api\/admin\/employees\/(\d+)$/))&&method==='PATCH'){const e=get('SELECT role FROM users WHERE id=?',+match[1]);if(e?.role!=='admin')fail('Фінансові права налаштовуються лише адміністратору');run('UPDATE users SET finance_access=? WHERE id=?',d.finance_access?1:0,+match[1]);audit(u,'employee.permissions',match[1],String(!!d.finance_access));return send({ok:true})}}
}
fail('Не знайдено',404);
}catch(e){const status=e.status||(/UNIQUE constraint/.test(e.message)?409:e.code==='ENOENT'?404:500);send({error:status===500?'Помилка сервера':status===409&&!e.status?'Запис із таким email, артикулом або штрихкодом уже існує':e.message},status)}});
const cleanup=setInterval(()=>{const now=Date.now();for(const [k,v]of limits)if(now-v.start>120000)limits.delete(k);run('DELETE FROM sessions WHERE expires<?',now)},60000);cleanup.unref();server.on('close',()=>{clearInterval(cleanup);s.db.close()});return {server,store:s,createUser};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {server}=createApp();server.listen(Number(process.env.PORT)||3000,process.env.HOST||'127.0.0.1',()=>console.log('Vitusik Shop: http://localhost:'+(process.env.PORT||3000)))}
