PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS roles(name TEXT PRIMARY KEY);
INSERT OR IGNORE INTO roles VALUES('owner'),('admin'),('seller'),('customer');
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE COLLATE NOCASE,phone TEXT NOT NULL DEFAULT '',password_hash TEXT NOT NULL,role TEXT NOT NULL REFERENCES roles(name),finance_access INTEGER NOT NULL DEFAULT 0,city TEXT DEFAULT '',branch TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS customers(user_id INTEGER PRIMARY KEY REFERENCES users(id));
CREATE TABLE IF NOT EXISTS employees(user_id INTEGER PRIMARY KEY REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS password_resets(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS brands(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,brand_id INTEGER NOT NULL REFERENCES brands(id),category_id INTEGER NOT NULL REFERENCES categories(id),sku TEXT NOT NULL UNIQUE,barcode TEXT UNIQUE,price INTEGER NOT NULL CHECK(price>0),cost INTEGER NOT NULL DEFAULT 0 CHECK(cost>=0),volume TEXT DEFAULT '',description TEXT DEFAULT '',characteristics TEXT DEFAULT '',ingredients TEXT DEFAULT '',usage TEXT DEFAULT '',image TEXT DEFAULT '',color TEXT DEFAULT '#f6edf1',active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),url TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS promotions(product_id INTEGER PRIMARY KEY REFERENCES products(id),price INTEGER NOT NULL CHECK(price>0),starts TEXT,ends TEXT);
CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,contact TEXT DEFAULT '',phone TEXT DEFAULT '',email TEXT DEFAULT '',site TEXT DEFAULT '',note TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS stock_receipts(id INTEGER PRIMARY KEY,supplier_id INTEGER REFERENCES suppliers(id),employee_id INTEGER REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,comment TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS expiration_lots(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),receipt_id INTEGER REFERENCES stock_receipts(id),quantity INTEGER NOT NULL CHECK(quantity>=0),expiry TEXT NOT NULL,cost INTEGER NOT NULL CHECK(cost>=0));
CREATE VIEW IF NOT EXISTS stock AS SELECT product_id,SUM(quantity) AS quantity FROM expiration_lots GROUP BY product_id;
CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),lot_id INTEGER REFERENCES expiration_lots(id),quantity INTEGER NOT NULL,type TEXT NOT NULL CHECK(type IN('receipt','sale','return','writeoff','adjustment','cancellation')),employee_id INTEGER REFERENCES users(id),balance INTEGER NOT NULL CHECK(balance>=0),comment TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,code TEXT NOT NULL UNIQUE,user_id INTEGER REFERENCES users(id),employee_id INTEGER REFERENCES users(id),channel TEXT NOT NULL CHECK(channel IN('online','pos')),name TEXT DEFAULT '',phone TEXT DEFAULT '',email TEXT DEFAULT '',status TEXT NOT NULL,total INTEGER NOT NULL CHECK(total>=0),comment TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),product_id INTEGER NOT NULL REFERENCES products(id),name TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),price INTEGER NOT NULL CHECK(price>0),cost INTEGER NOT NULL CHECK(cost>=0),returned INTEGER NOT NULL DEFAULT 0 CHECK(returned>=0 AND returned<=quantity),UNIQUE(order_id,product_id));
CREATE TABLE IF NOT EXISTS lot_allocations(id INTEGER PRIMARY KEY,order_item_id INTEGER NOT NULL REFERENCES order_items(id),lot_id INTEGER NOT NULL REFERENCES expiration_lots(id),quantity INTEGER NOT NULL CHECK(quantity>0),returned INTEGER NOT NULL DEFAULT 0 CHECK(returned>=0 AND returned<=quantity));
CREATE TABLE IF NOT EXISTS order_status_history(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),status TEXT NOT NULL,employee_id INTEGER REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),method TEXT NOT NULL,provider TEXT,status TEXT NOT NULL DEFAULT 'pending',amount INTEGER NOT NULL CHECK(amount>=0),external_id TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS deliveries(order_id INTEGER PRIMARY KEY REFERENCES orders(id),method TEXT NOT NULL,city TEXT DEFAULT '',branch TEXT DEFAULT '',tracking TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS pos_sales(order_id INTEGER PRIMARY KEY REFERENCES orders(id),employee_id INTEGER NOT NULL REFERENCES users(id));
CREATE TABLE IF NOT EXISTS returns(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),order_item_id INTEGER NOT NULL REFERENCES order_items(id),quantity INTEGER NOT NULL CHECK(quantity>0),amount INTEGER NOT NULL,employee_id INTEGER NOT NULL REFERENCES users(id),reason TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),user_id INTEGER NOT NULL REFERENCES users(id),rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),text TEXT NOT NULL,approved INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER NOT NULL REFERENCES users(id),product_id INTEGER NOT NULL REFERENCES products(id),PRIMARY KEY(user_id,product_id));
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY,order_id INTEGER REFERENCES orders(id),user_id INTEGER REFERENCES users(id),channel TEXT NOT NULL,recipient TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(order_id,channel));
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY,employee_id INTEGER REFERENCES users(id),action TEXT NOT NULL,entity TEXT NOT NULL,detail TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS products_brand ON products(brand_id);
CREATE INDEX IF NOT EXISTS products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS products_name ON products(name);
CREATE INDEX IF NOT EXISTS lots_fefo ON expiration_lots(product_id,expiry,quantity);
CREATE INDEX IF NOT EXISTS orders_customer_date ON orders(user_id,created_at);
CREATE INDEX IF NOT EXISTS orders_date ON orders(created_at,status);
CREATE INDEX IF NOT EXISTS movements_product ON stock_movements(product_id,created_at);
CREATE INDEX IF NOT EXISTS reviews_product ON reviews(product_id,approved);
