import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore,passwordHash} from './store.mjs';
import {createApp} from './index.mjs';
function fixture(){const s=createStore(),id=Number(s.run('INSERT INTO users(name,email,password_hash,role,finance_access) VALUES(?,?,?,?,?)','Owner','owner@example.test',passwordHash('test-password-123'),'owner',1).lastInsertRowid),u={id,role:'owner',finance_access:1};return {s,u}}
const order=(items=[{id:1,quantity:1}])=>({name:'Test',email:'test@example.test',phone:'+380000000000',delivery_method:'pickup',payment_method:'on_receipt',items});
test('public and seller product data never contain purchase prices',()=>{const {s,u}=fixture();assert.equal('cost' in s.productRows()[0],false);assert.equal('cost' in s.productRows({role:'seller'})[0],false);assert.equal('cost' in s.productRows({role:'admin',finance_access:0})[0],false);assert.equal(s.productRows(u)[0].cost,310);s.db.close()});
test('online and POS consume one shared stock, duplicate item IDs are consolidated',()=>{const {s,u}=fixture();s.createOrder(order([{id:1,quantity:2},{id:1,quantity:3}]),null);s.createOrder(order([{id:1,quantity:1}]),u,'pos');assert.equal(s.balance(1),9);assert.equal(s.get('SELECT COUNT(*) n FROM order_items WHERE order_id=1').n,1);s.db.close()});
test('insufficient stock rolls back the whole order and all allocations',()=>{const {s}=fixture();assert.throws(()=>s.createOrder(order([{id:1,quantity:1},{id:2,quantity:999}]),null));assert.equal(s.balance(1),15);assert.equal(s.get('SELECT COUNT(*) n FROM orders').n,0);s.db.close()});
test('FEFO selects earliest sellable lot and excludes expired inventory',()=>{const {s,u}=fixture();s.stockOperation({product_id:1,type:'receipt',quantity:2,cost:300,expiry:'2027-01-01',comment:'test'},u);s.stockOperation({product_id:1,type:'receipt',quantity:9,cost:300,expiry:'2020-01-01',comment:'expired'},u);const o=s.createOrder(order(),null),a=s.get('SELECT l.expiry FROM lot_allocations a JOIN expiration_lots l ON l.id=a.lot_id JOIN order_items i ON i.id=a.order_item_id WHERE i.order_id=?',o.id);assert.equal(a.expiry,'2027-01-01');assert.equal(s.productRows()[0].stock,16);s.db.close()});
test('returns restore original lots once; excessive and repeat returns fail',()=>{const {s,u}=fixture(),o=s.createOrder(order([{id:1,quantity:2}]),u,'pos');s.returnItems(o.id,{product_id:1,quantity:1,reason:'test'},u);assert.equal(s.balance(1),14);assert.throws(()=>s.returnItems(o.id,{product_id:1,quantity:2,reason:'test'},u));s.returnItems(o.id,{product_id:1,quantity:1,reason:'test'},u);assert.equal(s.balance(1),15);assert.throws(()=>s.returnItems(o.id,{product_id:1,quantity:1,reason:'test'},u));s.db.close()});
test('cancellation restores stock only once and cannot reopen terminal order',()=>{const {s,u}=fixture(),o=s.createOrder(order(),null);s.updateStatus(o.id,{status:'Скасовано'},u);s.updateStatus(o.id,{status:'Скасовано'},u);assert.equal(s.balance(1),15);assert.throws(()=>s.updateStatus(o.id,{status:'Нове'},u));s.db.close()});
test('status transitions create only one SMS outbox row at assembled status',()=>{const {s,u}=fixture(),o=s.createOrder(order(),null);assert.throws(()=>s.updateStatus(o.id,{status:'Зібрано'},u));for(const status of ['Прийнято','Збирається','Зібрано','Зібрано'])s.updateStatus(o.id,{status},u);assert.equal(s.get('SELECT COUNT(*) n FROM notifications WHERE order_id=?',o.id).n,1);s.db.close()});
test('profit uses purchase snapshot even after a later receipt; returns reduce revenue',()=>{const {s,u}=fixture(),o=s.createOrder(order([{id:1,quantity:2}]),u,'pos');s.stockOperation({product_id:1,type:'receipt',quantity:1,cost:450,expiry:'2028-01-01',comment:'new cost'},u);assert.equal(s.overview(u).profit,484);s.returnItems(o.id,{product_id:1,quantity:1,reason:'test'},u);assert.equal(s.overview(u).revenue,552);assert.equal(s.overview(u).profit,242);assert.equal('profit' in s.overview({role:'admin',finance_access:0}),false);s.db.close()});
test('HTTP auth, customer isolation, staff RBAC, CORS and public static assets',async()=>{const app=createApp({dbPath:':memory:'}),owner=app.createUser({name:'Owner',email:'o@example.test',password:'password-long-123'},'owner');app.createUser({name:'Seller',email:'s@example.test',password:'password-long-123'},'seller');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const root='http://127.0.0.1:'+app.server.address().port;try{const request=(p,m='GET',data,cookie,origin)=>fetch(root+p,{method:m,headers:{...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...(origin?{Origin:origin}:{})},body:data?JSON.stringify(data):undefined});assert.equal((await request('/')).status,200);assert.equal((await request('/api/admin/overview')).status,401);const login=await request('/api/auth/login','POST',{email:'s@example.test',password:'password-long-123'}),cookie=login.headers.get('set-cookie').split(';')[0];assert.equal(login.status,200);assert.equal((await request('/api/admin/products','GET',null,cookie)).status,403);assert.equal((await request('/api/pos/sales','POST',order(),cookie)).status,201);assert.equal((await request('/api/pos/sales','POST',order(),cookie,'https://evil.example')).status,403);const os=await(await request('/api/admin/orders','GET',null,cookie)).json();assert.equal('cost' in os[0].items[0],false);const reg=await request('/api/auth/register','POST',{name:'Customer',email:'c@example.test',phone:'+380000000000',password:'password-long-123'}),cc=reg.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/admin/orders','GET',null,cc)).status,403);assert.deepEqual(await(await request('/api/orders','GET',null,cc)).json(),[]);assert.equal((await request('/api/orders','POST',order(),cc)).status,201);assert.equal((await(await request('/api/orders','GET',null,cc)).json()).length,1);assert.equal((await request('/api/auth/login','POST',{email:owner.email,password:'wrong-password'})).status,401)}finally{await new Promise(r=>app.server.close(r))}});
